<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>smv</string>
	</array>
	<key>name</key>
	<string>NuSMV</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?-i:VAR|ASSIGN|FAIRNESS|TRANS|DEFINE|CONSTANTS|IVAR|INVAR|SPEC|CTLSPEC|LTLSPEC|PSLSPEC|COMPUTE|INVARSPEC|JUSTICE|COMPASSION|MODULE|ISA|CONSTRAINT|SIMPWFF|CTLWFF|LTLWFF|PSLWFF|COMPWFF)\b</string>
			<key>name</key>
			<string>keyword.control.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?-i:boolean|array|of|integer|real|word|word1|bool)\b</string>
			<key>name</key>
			<string>storage.type.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?-i:TRUE|FALSE)\b</string>
			<key>name</key>
			<string>constant.character.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?-i:EX|AX|EF|AF|EG|AG|E|F|O|G|H|X|Y|Z|A|U|S|V|R)\b</string>
			<key>name</key>
			<string>support.function.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?-i:process|case|esac|self)\b</string>
			<key>name</key>
			<string>keyword.operator.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?-i:init|next)\b</string>
			<key>name</key>
			<string>entity.name.function.nusmv</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>--</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nusmv</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.nusmv</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nusmv</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nusmv</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.nusmv</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$)[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>variable.other.nusmv</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nusmv</string>
	<key>uuid</key>
	<string>BACC2200-7894-11E3-981F-0800200C9A66</string>
</dict>
</plist>
